#!/usr/bin/env python

import sys
import os

# this scripts can open pscript search result

link = "open https://pursuit.purescript.org/search?q="
os.system(link + reduce(lambda x, y: x+"+"+y, sys.argv[1:]))
